name: Build, Test, and Run Java Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # Build the Java application
    - name: Build with Maven
      run: mvn clean package

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t java-hello-world .

    # Run the Docker container
    - name: Run Docker Container
      run: |
        docker run --rm java-hello-world

    # Verify output
    - name: Verify Output
      run: |
        if ! docker run --rm java-hello-world | grep -q "Hello, World!"; then
          echo "Expected output not found!"
          exit 1
        fi
